name: saikin
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/chatsen/saikin

environment:
  sdk: '>=3.0.0-189.0.dev <4.0.0'

dependencies:
  http: ^0.13.5
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^2.0.0
